on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ddvoteapp.azurecr.io
        username: ${{ secrets.acr_ddvoteapp_username }}
        password: ${{ secrets.acr_ddvoteapp_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/vote" -f  "vote/Dockerfile" -t ddvoteapp.azurecr.io/testddvoteapp:${{ github.sha }} --label dockerfile-path=vote/Dockerfile
        docker push ddvoteapp.azurecr.io/testddvoteapp:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_testddvoteapp_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ddvote | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ddvote`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ddvote
        container-registry-url: ddvoteapp.azurecr.io
        container-registry-username: ${{ secrets.acr_ddvoteapp_username }}
        container-registry-password: ${{ secrets.acr_ddvoteapp_password }}
        secret-name: testddvoteapdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ddvote
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          ddvoteapp.azurecr.io/testddvoteapp:${{ github.sha }}
        imagepullsecrets: |
          testddvoteapdockerauth
